name: link-check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose
            --no-progress
            --timeout 30
            --max-concurrency 5
            --retry-max-time 120
            https://raw.githubusercontent.com/trimstray/the-book-of-secret-knowledge/master/README.md
          fail: true